<?php

namespace Irajul\FilamentShadcnTheme\Enums;

enum StyleVariant: string
{
    case Vega = 'vega';
    case Nova = 'nova';
    case Maia = 'maia';
    case Lyra = 'lyra';
    case Mira = 'mira';
    case Luma = 'luma';
    case Sera = 'sera';

    /**
     * @return array<string, string>
     */
    public function variables(): array
    {
        return array_replace($this->baseVariables(), match ($this) {
            self::Vega => [
                'fs-style-density' => '1',
                'fs-control-height' => '2.375rem',
                'fs-control-height-sm' => '2rem',
                'fs-control-height-lg' => '2.625rem',
                'fs-control-padding-x' => '0.875rem',
                'fs-section-padding' => '1rem',
                'fs-card-padding-x' => '1.5rem',
                'fs-card-padding-y' => '1.5rem',
                'fs-card-radius' => 'var(--radius-xl)',
                'fs-font-size-sm' => '0.875rem',
                'fs-font-weight-medium' => '500',
            ],
            self::Nova => [
                'fs-style-density' => '0.95',
                'fs-control-height' => '2.25rem',
                'fs-control-height-sm' => '2rem',
                'fs-control-height-lg' => '2.5rem',
                'fs-control-padding-x' => '0.8125rem',
                'fs-main-padding-y' => '1rem',
                'fs-page-header-main-padding-y' => '0.75rem',
                'fs-page-header-main-gap' => '1.25rem',
                'fs-section-padding' => '0.875rem',
                'fs-card-padding-x' => '1.25rem',
                'fs-card-padding-y' => '1.25rem',
                'fs-card-radius' => 'var(--radius-xl)',
                'fs-sidebar-padding' => '0.5rem 0.75rem 0.75rem',
                'fs-font-size-sm' => '0.875rem',
                'fs-font-weight-medium' => '500',
            ],
            self::Maia => [
                'fs-style-density' => '1.08',
                'fs-control-height' => '2.625rem',
                'fs-control-height-sm' => '2.25rem',
                'fs-control-height-lg' => '2.875rem',
                'fs-control-padding-x' => '1rem',
                'fs-section-padding' => '1.25rem',
                'fs-card-padding-x' => '1.5rem',
                'fs-card-padding-y' => '1.5rem',
                'fs-card-radius' => 'var(--radius-2xl)',
                'fs-sidebar-item-height' => '2.25rem',
                'fs-font-size-sm' => '0.875rem',
                'fs-font-weight-medium' => '500',
            ],
            self::Lyra => [
                'fs-style-density' => '0.98',
                'fs-control-height' => '2.25rem',
                'fs-control-height-sm' => '1.875rem',
                'fs-control-height-lg' => '2.5rem',
                'fs-control-padding-x' => '0.75rem',
                'fs-section-padding' => '0.875rem',
                'fs-card-padding-x' => '1rem',
                'fs-card-padding-y' => '1rem',
                'fs-card-radius' => '0',
                'fs-focus-ring-width' => '1px',
                'fs-sidebar-item-radius' => '0',
                'fs-dropdown-item-radius' => '0',
                'fs-badge-radius' => '0',
                'fs-checkbox-radius' => '0',
                'fs-table-cell-padding-x' => '0.5rem',
                'fs-table-cell-padding-y' => '0.375rem',
                'fs-table-row-height' => '2.25rem',
                'fs-table-edge-padding-x' => '0.75rem',
                'fs-table-selection-cell-width' => '2.75rem',
                'fs-sidebar-padding' => '0.75rem 0.5rem 0.75rem',
                'fs-sidebar-group-padding' => '0',
                'fs-sidebar-section-gap' => '0.375rem',
                'fs-sidebar-item-padding-x' => '0.75rem',
                'fs-sidebar-item-padding-y' => '0.375rem',
                'fs-font-size-sm' => '0.8125rem',
                'fs-font-weight-medium' => '600',
            ],
            self::Mira => [
                'fs-style-density' => '0.88',
                'fs-control-height' => '2rem',
                'fs-control-height-sm' => '1.75rem',
                'fs-control-height-lg' => '2.25rem',
                'fs-control-padding-x' => '0.6875rem',
                'fs-section-padding' => '0.75rem',
                'fs-card-padding-x' => '1rem',
                'fs-card-padding-y' => '1rem',
                'fs-card-radius' => 'var(--radius-lg)',
                'fs-sidebar-item-height' => '1.875rem',
                'fs-font-size-sm' => '0.8125rem',
                'fs-font-weight-medium' => '500',
            ],
            self::Luma => [
                'fs-style-density' => '1.03',
                'fs-control-height' => '2.5rem',
                'fs-control-height-sm' => '2.125rem',
                'fs-control-height-lg' => '2.75rem',
                'fs-control-padding-x' => '1rem',
                'fs-section-padding' => '1rem',
                'fs-card-padding-x' => '1.5rem',
                'fs-card-padding-y' => '1.5rem',
                'fs-card-radius' => 'var(--radius-2xl)',
                'fs-sidebar-item-radius' => 'var(--radius-2xl)',
                'fs-font-size-sm' => '0.875rem',
                'fs-font-weight-medium' => '500',
            ],
            self::Sera => [
                'fs-style-density' => '1',
                'fs-control-height' => '2.5rem',
                'fs-control-height-sm' => '2.25rem',
                'fs-control-height-lg' => '2.75rem',
                'fs-control-padding-x' => '0.9375rem',
                'fs-section-padding' => '1.125rem',
                'fs-card-padding-x' => '1.5rem',
                'fs-card-padding-y' => '1.5rem',
                'fs-card-radius' => 'var(--radius-sm)',
                'fs-sidebar-item-radius' => 'var(--radius-sm)',
                'fs-font-size-sm' => '0.875rem',
                'fs-font-weight-medium' => '600',
            ],
        });
    }

    /**
     * @return array<string, string>
     */
    private function baseVariables(): array
    {
        return [
            'fs-body-font-size' => '0.875rem',
            'fs-line-height' => '1.5',
            'fs-control-height' => '2.25rem',
            'fs-control-height-sm' => '2rem',
            'fs-control-height-lg' => '2.5rem',
            'fs-control-padding-x' => '0.875rem',
            'fs-icon-size' => '1rem',
            'fs-main-padding-x' => '2rem',
            'fs-main-padding-y' => '1.75rem',
            'fs-page-gap' => '1.5rem',
            'fs-page-header-main-padding-y' => '0.75rem',
            'fs-page-header-main-gap' => '1.25rem',
            'fs-topbar-height' => '3.5rem',
            'fs-topbar-padding-x' => '1rem',
            'fs-topbar-start-gap' => '0.5rem',
            'fs-topbar-logo-order' => '1',
            'fs-topbar-collapse-button-order' => '2',
            'fs-topbar-collapse-button-margin-start' => '0.25rem',
            'fs-topbar-mobile-sidebar-button-desktop-display' => 'none',
            'fs-shell-divider-width' => '1px',
            'fs-shell-divider-color' => 'var(--border)',
            'fs-topbar-sidebar-divider-left' => 'var(--fs-sidebar-width)',
            'fs-collapsed-topbar-brand-display' => 'none',
            'fs-collapsed-topbar-start-width' => 'var(--fs-collapsed-sidebar-width)',
            'fs-collapsed-topbar-start-margin-start' => 'calc(var(--fs-topbar-padding-x) * -1)',
            'fs-collapsed-topbar-start-justify-content' => 'center',
            'fs-collapsed-topbar-start-gap' => '0',
            'fs-collapsed-topbar-collapse-button-margin-start' => '0',
            'fs-section-padding' => '1rem',
            'fs-card-gap' => '1.5rem',
            'fs-card-padding-x' => '1.5rem',
            'fs-card-padding-y' => '1.5rem',
            'fs-card-radius' => 'var(--radius-xl)',
            'fs-stat-gap' => '1rem',
            'fs-table-toolbar-padding-x' => '1rem',
            'fs-table-toolbar-padding-y' => '0.5rem',
            'fs-table-content-padding' => '0',
            'fs-table-header-background' => 'color-mix(in oklch, var(--muted) 58%, transparent)',
            'fs-table-row-hover-background' => 'color-mix(in oklch, var(--muted) 45%, transparent)',
            'fs-table-row-selected-background' => 'color-mix(in oklch, var(--muted) 70%, transparent)',
            'fs-table-header-cell-height' => '2.5rem',
            'fs-table-cell-padding-x' => '0.75rem',
            'fs-table-cell-padding-y' => '0.625rem',
            'fs-table-edge-padding-x' => '0.75rem',
            'fs-table-row-height' => '2.75rem',
            'fs-table-selection-cell-width' => '2.75rem',
            'fs-table-selection-cell-padding-left' => '0.75rem',
            'fs-table-selection-cell-padding-right' => '0.5rem',
            'fs-table-actions-gap' => '0.5rem',
            'fs-table-actions-padding-x' => '0.75rem',
            'fs-pagination-padding-x' => '1rem',
            'fs-pagination-padding-y' => '0.5rem',
            'fs-pagination-gap' => '0.75rem',
            'fs-pagination-height' => '3rem',
            'fs-sidebar-width' => '16rem',
            'fs-collapsed-sidebar-width' => '4rem',
            'fs-sidebar-padding' => '0.5rem 0.75rem 0.75rem',
            'fs-sidebar-header-height' => '3.5rem',
            'fs-sidebar-header-with-topbar-display' => 'none',
            'fs-sidebar-topbar-height' => 'calc(100svh - var(--fs-topbar-height))',
            'fs-collapsed-sidebar-top' => 'var(--fs-topbar-height)',
            'fs-collapsed-sidebar-height' => 'calc(100svh - var(--fs-topbar-height))',
            'fs-sidebar-group-padding' => '0.5rem',
            'fs-sidebar-group-gap' => '0.5rem',
            'fs-sidebar-section-gap' => '1rem',
            'fs-sidebar-item-gap' => '0.25rem',
            'fs-sidebar-item-height' => '2rem',
            'fs-sidebar-item-padding-x' => '0.5rem',
            'fs-sidebar-item-padding-y' => '0.375rem',
            'fs-sidebar-item-radius' => 'var(--radius-md)',
            'fs-sidebar-label-height' => '2rem',
            'fs-sidebar-group-rail-display' => 'none',
            'fs-dropdown-padding' => '0.25rem',
            'fs-dropdown-item-height' => '2rem',
            'fs-dropdown-item-radius' => 'var(--radius-sm)',
            'fs-badge-radius' => 'var(--radius-md)',
            'fs-focus-ring-width' => '3px',
            'fs-input-shadow' => '0 1px 2px 0 oklch(0 0 0 / 0.05)',
            'fs-input-background' => 'transparent',
            'fs-dark-input-background' => 'color-mix(in oklch, var(--input) 30%, transparent)',
            'fs-checkbox-size' => '1rem',
            'fs-checkbox-radius' => '4px',
            'fs-checkbox-background' => 'color-mix(in oklch, var(--background) 86%, var(--foreground) 8%)',
            'fs-checkbox-border-color' => 'color-mix(in oklch, var(--input) 82%, var(--foreground) 18%)',
            'fs-checkbox-checked-background' => 'var(--primary)',
            'fs-checkbox-checked-border-color' => 'var(--primary)',
            'fs-checkbox-checked-color' => 'var(--primary-foreground)',
            'fs-checkbox-checked-icon' => 'url("data:image/svg+xml;charset=utf-8,%3Csvg viewBox=\'0 0 16 16\' fill=\'%23fff\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cpath d=\'M12.207 4.793a1 1 0 0 1 0 1.414l-5 5a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L6.5 9.086l4.293-4.293a1 1 0 0 1 1.414 0z\'/%3E%3C/svg%3E")',
            'fs-checkbox-indeterminate-icon' => 'url("data:image/svg+xml;charset=utf-8,%3Csvg viewBox=\'0 0 16 16\' fill=\'%23fff\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cpath d=\'M4.5 6.75a1.25 1.25 0 0 0 0 2.5h7a1.25 1.25 0 0 0 0-2.5h-7z\'/%3E%3C/svg%3E")',
            'fs-dark-checkbox-checked-icon' => 'url("data:image/svg+xml;charset=utf-8,%3Csvg viewBox=\'0 0 16 16\' fill=\'%231c1917\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cpath d=\'M12.207 4.793a1 1 0 0 1 0 1.414l-5 5a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L6.5 9.086l4.293-4.293a1 1 0 0 1 1.414 0z\'/%3E%3C/svg%3E")',
            'fs-dark-checkbox-indeterminate-icon' => 'url("data:image/svg+xml;charset=utf-8,%3Csvg viewBox=\'0 0 16 16\' fill=\'%231c1917\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cpath d=\'M4.5 6.75a1.25 1.25 0 0 0 0 2.5h7a1.25 1.25 0 0 0 0-2.5h-7z\'/%3E%3C/svg%3E")',
            'fs-loading-section-min-height' => '7rem',
            'fs-skeleton-line-height' => '0.75rem',
            'fs-skeleton-line-radius' => '999px',
            'fs-skeleton-title-width' => '36%',
            'fs-skeleton-body-width' => '64%',
            'fs-skeleton-line-gap' => '2rem',
            'fs-skeleton-opacity' => '0.45',
            'fs-skeleton-active-opacity' => '0.75',
            'fs-skeleton-animation-duration' => '1.4s',
            'fs-transition-duration' => '150ms',
        ];
    }
}
